FROM mcr.microsoft.com/dotnet/sdk:6.0
WORKDIR /src/KachnaOnline.App
EXPOSE 5000
EXPOSE 5001
RUN dotnet dev-certs https
# Change if your timezone is different
ENV TZ=Europe/Prague
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENTRYPOINT ["./runapi.sh"]
